"""Pydantic models for MCP responses."""

from .core import (
    AnalysisResult,
    ClassInfo,
    ContextualExtractionResult,
    CrawlClassInfo,
    CrawlFileResult,
    CrawlFunctionInfo,
    CrawlSummary,
    ExecutionPath,
    FileContextResult,
    FunctionInfo,
    GeneratedTestCase,
    PatchResultModel,
    PathCondition,
    ProjectCrawlResult,
    RefactorSecurityIssue,
    RefactorSimulationResult,
    SurgicalExtractionResult,
    SymbolicResult,
    SymbolReference,
    SymbolReferencesResult,
    TestGenerationResult,
    UnifiedDetectedSink,
    UnifiedSinkResult,
    VulnerabilityInfo,
)
from .context import Language, SourceContext, ProjectContext, FileMetadata
from .envelope import SchemaVersion, ResponseEnvelope
from .policy import (
    CodePolicyCheckResult,
    PathValidationResult,
    PolicyVerificationResult,
)
from .security import (
    DependencyInfo,
    DependencyScanResult,
    DependencyScanResultModel,
    DependencyVulnerability,
    SecurityResult,
    TypeEvaporationResultModel,
    VulnerabilityFindingModel,
)

__all__ = [
    "AnalysisResult",
    "ClassInfo",
    "ContextualExtractionResult",
    "CrawlClassInfo",
    "CrawlFileResult",
    "CrawlFunctionInfo",
    "CrawlSummary",
    "ExecutionPath",
    "FileContextResult",
    "FunctionInfo",
    "GeneratedTestCase",
    "PatchResultModel",
    "PathCondition",
    "ProjectCrawlResult",
    "RefactorSecurityIssue",
    "RefactorSimulationResult",
    "SurgicalExtractionResult",
    "SymbolicResult",
    "SymbolReference",
    "SymbolReferencesResult",
    "TestGenerationResult",
    "UnifiedDetectedSink",
    "UnifiedSinkResult",
    "VulnerabilityInfo",
    "DependencyInfo",
    "DependencyScanResult",
    "DependencyScanResultModel",
    "DependencyVulnerability",
    "SecurityResult",
    "TypeEvaporationResultModel",
    "VulnerabilityFindingModel",
    "CodePolicyCheckResult",
    "PathValidationResult",
    "PolicyVerificationResult",
    # Context models
    "Language",
    "SourceContext",
    "ProjectContext",
    "FileMetadata",
    # Response envelope
    "SchemaVersion",
    "ResponseEnvelope",
]
